version: '3.8'

services:
  sosyoussoufiawebapp:
    build:
      context: .
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/sosyoussoufiawebapp
    healthcheck:
      disable: true
    image: web-app:react-web-app
    container_name: web-app
    command: npm start

volumes:
  notused: